prefix: ./greenwich-conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch==2.8.0
    - torchvision==0.23.0
    - matplotlib==3.10.6
    - sympy
    - hydra-core==1.3
    - pinnstorch
    - nbstripout
  - lightning
  - deepxde
  - ipython
  - ipykernel
  - ipympl
